# MongoDB user password secret.
# Required by the MongoDB Community Operator.
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
  namespace: mongodb
type: Opaque
stringData:
  password: password
